envs:
  confidence_port: 3001
  flow_port:       3002
  workspace_port:  3003

server_http:
  testers: ["127.0.0.1"]

sqlite:
  path: "/home/pavlo/0/_datastore/local.sqlite"

mongodb:
  host: "localhost"
  port: 27017

smtp:
  host: "smtp.mailtrap.io"
  port: 2525
  user: "c889a7509fd7e7"
  pass: "117335db87915f"

pop3:
  host: "pop.zoho.com:995"
  user: "pavlo67@zoho.com"
  pass: "p@dzfsamuZ1"
